[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Set this to true to enable Next.js src directory support
    src_dir = "src"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
